### ISSUE TITLE
Add 100% keyboard layout

### ISSUE THREAD

**Issue by bloznelis** [bloznelis/kbt#1]

**Comment by 0x61nas** [comment]
I can work on this feature if u don't mind

**Comment by bloznelis** [comment]
Sure, go ahead @0x61nas !

**Comment by 0x61nas** [comment]
Then could you assign this issue to me?

**Comment by bloznelis** [comment]
Any progress on this @0x61nas ?

**Comment by 0x61nas** [comment]
Oh, Sorry but I can't get enough time to work on this, I did take a look at the code and it has a lot of boilerplate code I think that you might want to work on this, sorry again
