### ISSUE TITLE
Does not work over ssh

### ISSUE THREAD

**Issue by cheater** [bloznelis/kbt#26]
I wanted to try kbt to debug some issues with recognizing keyboard combinations over ssh, but the program requires an X server running.

Consider using an input method that does not require X, only what the terminal gives it.

I understand if it's far outside what you want to do with this program.

**Comment by bloznelis** [comment]
Terminal can only capture a subset of all available keystrokes. So it boils down to not being outside this program, but not enough.

**Comment by cheater** [comment]
hmm what keystrokes cannot be captured via the terminal? out of curiosity.

**Comment by bloznelis** [comment]
Most of the modifiers, like shift for example, does not send any signal to the terminal if pressed alone. Even seemingly trivial things like [backspace](https://github.com/bloznelis/typioca/issues/68#issuecomment-1176295495) are hacked in. I would have been very glad to have this working with terminal keystrokes only, believe me :D
