### ISSUE TITLE
WSL support?

### ISSUE THREAD

**Issue by kristianbinau** [bloznelis/kbt#7]
It seems to not work in [WSL](https://learn.microsoft.com/en-us/windows/wsl/),.. 

I can compile and start, but when i click enter to select a layout nothing happens.   
If i resize the window it updates and shows the keyboard. But the keyboard window wont update, so nothing happens.

### System:
**Windows:**
Edition: Windows 11 Pro
Version: 22H2
OS build: 22621.1992
Experience: Windows Feature Experience Pack 1000.22644.1000.0

**WSL:**
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1992

**WSL OS:**
Ubuntu 22.04.1 LTS

**Comment by bloznelis** [comment]
It only works in systems running Xorg, as this is the way how it captures the key presses. I do not forsee Windows support in the near future as I have no means to test it.

**Comment by bloznelis** [comment]
Since the 2.0.0 we support Windows, this could be tested again @kristianbinau

**Comment by kristianbinau** [comment]
It's unfortunately still doesn't work in WSL for me : (
But it works great in Windows Powershell, so I'm just gonna use it there : ) 

Awesome work! 🥇

**Comment by bloznelis** [comment]
Alrighty, I'm closing this one then.
