### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by bloznelis** [bloznelis/kbt#8]
Explore and implement, if possible, `backend::KeyBackend` for MacOS.

**Comment by bloznelis** [comment]
In theory this could be working now. Anyone on MacOS can test it maybe?

**Comment by haunt98** [comment]
Hi @bloznelis, I have tested on my mac. It's looking good!

First open will require accessibility permisison from settings.

<img width="764" alt="image" src="https://github.com/bloznelis/kbt/assets/5424272/d921e0f3-4521-4dc0-b1f2-fbc38f9f645e">


Next time all good!

<img width="1688" alt="image" src="https://github.com/bloznelis/kbt/assets/5424272/92a74b4c-4edd-4eb3-b46a-86f1ef223124">

**Comment by bloznelis** [comment]
Thanks, the permission part is expected. Nice to see it working, will package it to homebrew!
